CREATE TABLE `luna_follower_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`followerCount` int NOT NULL,
	`followingCount` int NOT NULL DEFAULT 0,
	`totalPosts` int NOT NULL DEFAULT 0,
	`snapshotDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `luna_follower_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `luna_post_tracker` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduledPostId` int,
	`igPostId` varchar(128),
	`igPermalink` text,
	`format` enum('reel','carousel','post','story','live') NOT NULL,
	`topic` varchar(255) NOT NULL,
	`caption` text,
	`thumbnailUrl` text,
	`publishedAt` timestamp NOT NULL,
	`weekNumber` int,
	`pillar` enum('education','emotion','promotion','social_proof','entertainment') NOT NULL DEFAULT 'education',
	`ctaType` enum('dm_keyword','link_in_bio','comment','save','share','none') NOT NULL DEFAULT 'link_in_bio',
	`ctaKeyword` varchar(64),
	`reach` int NOT NULL DEFAULT 0,
	`impressions` int NOT NULL DEFAULT 0,
	`plays` int DEFAULT 0,
	`avgWatchTimeSec` int,
	`watchThroughRate` int DEFAULT 0,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`saves` int NOT NULL DEFAULT 0,
	`shares` int NOT NULL DEFAULT 0,
	`engagementRateBp` int NOT NULL DEFAULT 0,
	`profileVisits` int NOT NULL DEFAULT 0,
	`linkClicks` int NOT NULL DEFAULT 0,
	`dmsReceived` int NOT NULL DEFAULT 0,
	`dmConversions` int NOT NULL DEFAULT 0,
	`attributedRevenueCents` int NOT NULL DEFAULT 0,
	`newFollowers` int NOT NULL DEFAULT 0,
	`unfollows` int DEFAULT 0,
	`viralityScore` int DEFAULT 0,
	`aiInsight` text,
	`repostCandidate` int NOT NULL DEFAULT 0,
	`dataSource` enum('manual','api_sync') NOT NULL DEFAULT 'manual',
	`lastSyncedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `luna_post_tracker_id` PRIMARY KEY(`id`)
);
